version: '3.7'

services:
  front:
    build: front
    ports:
      - "5000:5000"

  back:
    build: back
    ports:
      - "8000:8000"
    volumes:
      - ./logs.txt:/app/logs.txt

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
