version: '3.7'

services:
  front:
    build: front
    expose:
      - "5000"

  back:
    build: back
    expose:
      - "8000"
    volumes:
      - ./logs.txt:/app/logs.txt

  redis:
    image: redis
    expose:
      - "6379"
    container_name: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    container_name: postgres

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"
