version: '3.7'

services:
  front:
    build: front
    expose:
      - "5000"

  back:
    build: back
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./logs.txt:/app/logs.txt

  redis:
    image: redis
    expose:
      - "6379"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"
